### ISSUE TITLE
Unknow format on Encode Axis with a DataTime data

### ISSUE THREAD

**Issue by rraires** [domoritz/streamlit-vega-lite#17]
I´m trying to use to select a period of a temporal series (Stocks DataFrame), but the date formatting on the x-axis has an unknown format.
When I plot de chart without "altair_component" component, the date format is ok.

Here is the code:

```py
import streamlit as st
import pandas as pd
from pandas_datareader import data
import numpy as np
import altair as alt
from streamlit_vega_lite import vega_lite_component, altair_component
start = '2020-1-1'
end = '2020-12-31'
source = 'yahoo'
stocks = data.DataReader("AAPL", start=start ,end=end, data_source=source).reset_index()[["Date", "Close"]]
stocks.rename(columns={'Date': 'x'}, inplace = True)
@st.cache
def linechart():
	brushed = alt.selection_interval(encodings=['x'], name="brushed")
	return (
			alt.Chart(stocks).mark_line().
			encode(
				alt.X('x', type = 'temporal'),
				alt.Y('Close')
			).
			properties(height=300, width=500).
			add_selection(brushed)
	)
event = altair_component(linechart())
selection = event.get('x')
st.write(selection)
```

![image](https://user-images.githubusercontent.com/7855963/133956688-de4d8421-0750-4315-a386-c17db1dda677.png)

**Comment by domoritz** [comment]
It looks like you only have a few minutes of data. It all seems correct. You can change the format manually if you want to understand the data better.

**Comment by rraires** [comment]
Domoritz, thanks for your return. I change the format of datatime column for YYYY-mm-dd instead a full datatime data ( YYYY-mm-dd Z000:000000 XXXXXX) and is ok! Thanks for the support and congrats for the component. Its a great feature! Regards!

**Comment by domoritz** [comment]
You're very welcome.
