### ISSUE TITLE
Interaction between Altair Selection and Streamlit Selection

### ISSUE THREAD

**Issue by jbpauly** [domoritz/streamlit-vega-lite#9]
Curious to know if it's possible to have bi-directional functionality between an Altair Chart `selection` and a Streamlit `selectbox` using `streamlit-vega-lite`. 

I'm working to build interactivity between a correlation matrix and a scatter plot similar to this [example](https://towardsdatascience.com/altair-plot-deconstruction-visualizing-the-correlation-structure-of-weather-data-38fb5668c5b1). In this example, it isn't possible to change the `labels` of the X and Y axes on scatter plot based on selection in the correlation matrix. Additionally, it's difficult to use the selections in Altair for inputs in other functions.

So, my thought is to create the scatter off of Streamlit `selectbox` selections (var1 / var2 or xaxis / yaxis). To keep the interactions with the correlation matrix, I need bi-directional functionality between the Streamlit selection boxes and the Altair Chart selection. This would also enable the Altair selection to be utilized for other purposes beyond Chart filtering and transforms. 

Just starting to work on it now and thought to ask if I'm working on a dead end task.

**Comment by cadasa** [comment]
I'd also love to have this bi-directional functionality between an Altair Chart selection and Streamlit

**Comment by domoritz** [comment]
Altair Selections are Vega-Lite selections, which are implemented as Vega signals (I don't have time to go into the details here). Vega signals that represent the Vega-Lite/Altair selections is what this plugin listens to and send to Python (i.e. Streamlit). I have not yet implemented the reverse but it's possible. 

Hope this answers your question. If not, I encourage you to look into the code. It's pretty short.
